name = "591-rent-bot"
main = "src/index.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "rent-bot-db"
database_id = "b90b0324-75f0-43be-87bf-7e10dc48582c"

[triggers]
crons = ["0 * * * *"]
